name: image_resize
description: "An app to enable users to select one or more images to resize."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  file_picker: ^10.3.6
  flutter:
    sdk: flutter
  image: ^4.5.4
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
