name: image_resize
description: "An app to enable users to select one or more images to resize."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  image: ^4.7.2
  image_gallery_saver: ^2.0.3
  image_picker: ^1.2.1
  multi_cloud_storage: ^0.6.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Inter-Black.otf
          weight: 900
        - asset: assets/fonts/Inter-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter-BlackItalic.otf
          weight: 900
          style: italic
